# Generated by Django 3.0.3 on 2020-03-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("placementApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile_images/default.png",
                null=True,
                upload_to="profile_images",
            ),
        ),
    ]
