# Generated by Django 3.0.3 on 2020-03-16 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placementApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('S', 'Super Dream'), ('D', 'Dream'), ('R', 'Regular')], max_length=1)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('vacancies', models.IntegerField(default=0)),
                ('interview_date', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('package', models.IntegerField(default=0)),
                ('details', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placementApp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Put Under Review'), ('2', 'Scheduled For Interview'), ('3', 'Selected'), ('4', 'Rejected')], default='1', max_length=1)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placementApp.Position')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placementApp.Student')),
            ],
        ),
    ]
